# Generated by Django 6.1.1 on 2026-09-28 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('verify_email', 'Verify email'), ('reset_password', 'Reset password')], default='verify_email', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'purpose', '-created_at'], name='acct_otp_email_purpose_dt_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailotp',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ('verify_email', 'reset_password'))), name='accounts_otp_purpose_valid'),
        ),
    ]
