# Generated by Django 6.1.1 on 2026-09-30 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminaccessrequest'),
        ('events', '0002_eventregistration'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_registered_for_event', 'User registered for event'), ('registration_cancelled', 'Registration cancelled'), ('task_created', 'Task created'), ('task_assigned', 'Task assigned'), ('task_updated', 'Task updated'), ('task_status_changed', 'Task status changed'), ('admin_access_requested', 'Admin access requested'), ('admin_access_approved', 'Admin access approved'), ('admin_access_rejected', 'Admin access rejected')], max_length=32)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('target_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='events.event')),
                ('target_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='events.eventregistration')),
                ('target_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.task')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['actor', '-created_at'], name='acct_activity_actor_dt'), models.Index(fields=['target_user', '-created_at'], name='acct_activity_target_dt'), models.Index(fields=['action_type', '-created_at'], name='acct_activity_action_dt')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action_type__in', ('user_registered_for_event', 'registration_cancelled', 'task_created', 'task_assigned', 'task_updated', 'task_status_changed', 'admin_access_requested', 'admin_access_approved', 'admin_access_rejected'))), name='accounts_activity_action_valid')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('event_registration', 'Event registration'), ('registration_cancelled', 'Registration cancelled'), ('task_assigned', 'Task assigned'), ('task_updated', 'Task updated'), ('admin_access_request', 'Admin access request'), ('admin_access_approved', 'Admin access approved'), ('admin_access_rejected', 'Admin access rejected'), ('system', 'System')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_type', models.CharField(blank=True, default='', max_length=32)),
                ('related_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='acct_notif_rec_read_dt'), models.Index(fields=['recipient', '-created_at'], name='acct_notif_rec_dt_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ('event_registration', 'registration_cancelled', 'task_assigned', 'task_updated', 'admin_access_request', 'admin_access_approved', 'admin_access_rejected', 'system'))), name='accounts_notification_category_valid')],
            },
        ),
    ]
