# Generated by Django 6.1.1 on 2026-09-29 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled')], default='registered', max_length=12)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-registered_at', '-pk'),
                'indexes': [models.Index(fields=['user', 'status', '-registered_at'], name='event_reg_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='event_registration_unique_user'), models.CheckConstraint(condition=models.Q(('status__in', ('registered', 'cancelled'))), name='event_registration_status_valid')],
            },
        ),
    ]
