# Generated by Django 6.1.1 on 2026-09-29 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_eventregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='todo', max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=8)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_event_tasks', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='events.event')),
            ],
            options={
                'ordering': ('due_at', 'pk'),
                'indexes': [models.Index(fields=['event', 'status'], name='tasks_event_status_idx'), models.Index(fields=['assignee', 'status'], name='tasks_assignee_status_idx'), models.Index(fields=['due_at'], name='tasks_due_at_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('todo', 'in_progress', 'completed', 'cancelled'))), name='tasks_status_valid'), models.CheckConstraint(condition=models.Q(('priority__in', ('low', 'medium', 'high', 'urgent'))), name='tasks_priority_valid')],
            },
        ),
    ]
